Public Class DeleteUser
    Private SQL As New SQLControll

    Private Sub DeleteUser_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        MdiParent = Form1
        FetchUsers()
    End Sub

    Private Sub FetchUsers()
        'REFRESH USER LIST
        clbUsers.Items.Clear()

        'ADD PARAMS & RUN QUERY
        SQL.AddParams("@Users", "%" & txtFilter.Text & "%")
        SQL.ExecQuery("SELECT username " &
                      "FROM members " &
                      "WHERE Username LIKE @Users ORDER BY username;")

        'REPORT AND ABORT
        If SQL.HasException(True) Then Exit Sub

        'LOOP ROWS AND RETURN USERS TO OUR LIST
        For Each r As DataRow In SQL.DBDT.Rows
            clbUsers.Items.Add(r("username"))
        Next
    End Sub

    Private Sub DeleteUsers()
        If MsgBox("the selected users will be deleted, are you sure?", MsgBoxStyle.YesNo, "Delete user") = MsgBoxResult.Yes Then


            'GENERATE MASS  DELETE COMMAND
            Dim c As Integer ' unique id for autogenerated members
            Dim DelString As String = "" ' query string builder


            For Each i As String In clbUsers.CheckedItems
                SQL.AddParams("@user" & c, i)
                DelString += "DELETE FROM members WHERE username = @user" & c & ";"
                c += 1
            Next

            SQL.ExecQuery(DelString)

            If SQL.HasException(True) Then Exit Sub

            MsgBox("users deleted!!")

            'REFRESH LIST
            FetchUsers()

        End If
    End Sub

    Private Sub txtFilter_KeyDown(sender As Object, e As KeyEventArgs) Handles txtFilter.KeyDown
        If e.KeyCode = Keys.Enter Then
            FetchUsers()
            e.Handled = True
            e.SuppressKeyPress = True
        End If
    End Sub

    Private Sub cmdDelete_Click(sender As Object, e As EventArgs) Handles cmdDelete.Click
        DeleteUsers()

    End Sub
End Class